---
title: "Arbeidskrav_reliabilitet"
author: 'null'
output:
  word_document: default
  html_document: default
  pdf_document: default
---

##Introduksjon

Maksimalt oksygenopptak ble først beskrevet av Hill og Lupton i 1923, og kan defineres som kroppens evne
til å ta opp og forbruke oksygen per tidsenhet(Hill & Lupton, 1923, Basset & Howley, 2000). Innen
toppidrett måles ofte det maksimale oksygenopptaket for å måle utøverens kapasitet opp mot arbeidskravet
i den spesifikke idretten, og det maksimale oksygenopptaket kan i så måte også sees på som et mål på den
aerobe kapasiteten til utøveren (Bahr et al 1992). I Olympiatoppens testprotokoller benytter de flere
definerte hjelpekriterier for å sikre at man faktisk har funnet deltakerens maksimale oksygenopptak
(Tønnesen et al, 2017). Følgende kriterier er beskrevet; platå i V'O2 er oppnådd, økning i ventilasjon
med utflating av V'O2 verdi, RER over 1.10/1.05, og blodlaktat over 8.


##Metode

I forkant av testen målte alle deltakerne kroppsvekt på en vekt plassert i laben. Deltakerne målte
kroppsvekten i samme klær som de skulle gjennomføre testen, men ble bedt om å ta av seg skoene.
Kroppsvekten som senere brukt i beregningen av maksimalt oksygenopptak (ml/min/kg) er kroppsvekten målt i
forkant av test, etter at 300g har blitt trukket av for å ta høyde for vekten av klærne. For å sikre
intern validitet ble deltakerne bedt om å avstå fra anstrengende fysisk aktivitet dagen før test, samt
avstå fra inntak av koffein de siste 12 timene før testen(Halperin, 2015). Pre- og post-tester ble
gjennomført på samme tid på døgnet, i tillegg til at deltakerne ble bedt om å innta det samme måltidet
før både pre og post-test. Alle tester ble også gjennomført under samme romforhold og temperatur, i
tillegg til at alle deltakerne benyttet seg av samme skotøy på både pre- og post-test. 

Alle deltakerne gjennomførte en 10 minutter lang oppvarmingsprotokoll på tredemøllen (Woodway), beskrevet
for deltakerne i forkant av testen. Denne oppvarmingsprotokollen bestod av fem minutter på 11-13 i Borg
6-20 RPE skala (Borg,1982), etterfulgt av 2x1min på starthastighet og stigning. Starthastighet for begge
kjønn var satt til 8km/t, med stigning på 10,5% og 5,5% for henholdsvis menn og kvinner. 

Maksimalt oksygenopptak (Vo2max) ble målt ved hjelp av en metabolsk analysator med miksekammer (Vyntus
CareFusion). Forut for alle tester ble analysatoren gass og volumkalibrert med en feillmargin på
henholdsvis 2% og 0,2%. Analysatoren ble stilt inn til å gjøre målinger hvert 30sek, og Vo2max ble
kalkulert gjennom å bruke snittet av de to høyeste målingene av V’O2. Underveis i testen mottok alle
deltakerne en høylytt verbal oppmuntring fra testleder. Alle deltakerne gjennomførte også begge testene
med samme testleder og med samme personer til stede i rommet for å redusere konfundering(Halperin, 2015).


For hvert medgåtte minutt av testen ble hastigheten på møllen økt med 1km/t, helt til utmattelse, hvor
testen ble avsluttet. Deltakernes hjertefrekvens(GARMIN/POLAR) ble også registrert under hele testen. Når
testen ble avsluttet ble deltakerne bedt om å rapportere opplevd anstrengelse ved hjelp av Borg-skala
(Borg,1982). Maksimal hjertefrekvens under testen ble også registrert. Ett minutt etter avsluttet test ble hjertefrekvens registrert, og det ble målt og analysert blodlaktat(BIOSEN). 


##Diskusjon

Ettersom mølletesting av maksimalt oksygenopptak er en test som gjennomføres til utmattelse, vil man
kunne forvente en viss variasjon i testresultatene ettersom opplevd anstrengelse kan påvirkes av flere
ulike variabler(Halperin, 2015). For å redusere konfundering vil flere faktorer være nyttig å ta hensyn
til under slik testing. Som nevnt i metoden vil standardisering av matinntak, koffeininntak, utstyr og
tidspunkt for gjennomføring av test være med på å kunne sikre intern validitet i resultatene. Eksempler
er deltakernes kjennskap til testen, verbal oppmuntring og personer tilstede under testen er andre
faktorer som potensielt kan bidra til konfundering. Felles for alle faktorer er at graden av påvirkning
på resultatene muligens reduseres ved hjelp av en standardisert testprotokoll. Deltakerne - og
testlederne, sin kjennskap til testen er en annen faktor som trolig påvirker resultatene i vårt prosjekt.
I dette tilfellet fantes det enkelte deltakere som hadde gjennomført en liknende test flere ganger, og en
kan da forvente en mindre grad av variasjon mellom resultatene på pre og post test, sammenlignet med de
deltakerne som gjennomførte testen for første gang på pretest. Dette fordi kjennskapen og kunnskapen de
tilegnet seg på pre-test, trolig spiller inn på testresultatene. Standardfeilen på (SETT INN) kan også
tyde på at enkelte av disse resultatene kan være utsatt for konfundering av ulik sort(Hopkins,2000). 



```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(readxl)
library(tidyverse)

dat <- read_excel("data/vo2g1.xlsx") %>%
  mutate(diff = ) %>%
  
  summarise(s = sd(diff), 
            te = s / sqrt (2),
            m = mean(c(),
            cv = ((te / m) * 100) %>%
              
cv <- round(dat$cv, 2)


  print()
  
  



```

